name: "Assemble"

on:
    pull_request:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

concurrency:
    group: assemble-flavors-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    flavor:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                flavor: [ Generic, Gplay, Huawei ]
        steps:
            -   uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            -   name: set up JDK 17
                uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
                with:
                    distribution: "temurin"
                    java-version: 17
            -   name: Build ${{ matrix.flavor }}
                run: |
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" >> gradle.properties
                    ./gradlew assemble${{ matrix.flavor }}
